# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEncuesta.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmEncuesta(object):
    def setupUi(self, frmEncuesta):
        frmEncuesta.setObjectName("frmEncuesta")
        frmEncuesta.resize(503, 593)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        frmEncuesta.setFont(font)
        self.centralwidget = QtWidgets.QWidget(frmEncuesta)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRegistrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistrar.setGeometry(QtCore.QRect(380, 10, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.btnRestablecer = QtWidgets.QPushButton(self.centralwidget)
        self.btnRestablecer.setGeometry(QtCore.QRect(380, 80, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnRestablecer.setFont(font)
        self.btnRestablecer.setObjectName("btnRestablecer")
        self.btnEvaluar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvaluar.setGeometry(QtCore.QRect(380, 150, 91, 51))
        self.btnEvaluar.setObjectName("btnEvaluar")
        self.lbVehiculo = QtWidgets.QLabel(self.centralwidget)
        self.lbVehiculo.setGeometry(QtCore.QRect(30, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbVehiculo.setFont(font)
        self.lbVehiculo.setObjectName("lbVehiculo")
        self.lbDias = QtWidgets.QLabel(self.centralwidget)
        self.lbDias.setGeometry(QtCore.QRect(30, 50, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbDias.setFont(font)
        self.lbDias.setObjectName("lbDias")
        self.lbKm = QtWidgets.QLabel(self.centralwidget)
        self.lbKm.setGeometry(QtCore.QRect(30, 90, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbKm.setFont(font)
        self.lbKm.setObjectName("lbKm")
        self.cmbVehiculo = QtWidgets.QComboBox(self.centralwidget)
        self.cmbVehiculo.setGeometry(QtCore.QRect(200, 10, 161, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbVehiculo.setFont(font)
        self.cmbVehiculo.setObjectName("cmbVehiculo")
        self.spbDias = QtWidgets.QSpinBox(self.centralwidget)
        self.spbDias.setGeometry(QtCore.QRect(200, 50, 41, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spbDias.setFont(font)
        self.spbDias.setMinimum(1)
        self.spbDias.setMaximum(7)
        self.spbDias.setObjectName("spbDias")
        self.leKm = QtWidgets.QLineEdit(self.centralwidget)
        self.leKm.setGeometry(QtCore.QRect(190, 90, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leKm.setFont(font)
        self.leKm.setObjectName("leKm")
        self.gbCalificacion = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCalificacion.setGeometry(QtCore.QRect(20, 120, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.gbCalificacion.setFont(font)
        self.gbCalificacion.setObjectName("gbCalificacion")
        self.optMB = QtWidgets.QRadioButton(self.gbCalificacion)
        self.optMB.setGeometry(QtCore.QRect(20, 20, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.optMB.setFont(font)
        self.optMB.setObjectName("optMB")
        self.optB = QtWidgets.QRadioButton(self.gbCalificacion)
        self.optB.setGeometry(QtCore.QRect(20, 50, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.optB.setFont(font)
        self.optB.setObjectName("optB")
        self.optR = QtWidgets.QRadioButton(self.gbCalificacion)
        self.optR.setGeometry(QtCore.QRect(20, 80, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.optR.setFont(font)
        self.optR.setObjectName("optR")
        self.optM = QtWidgets.QRadioButton(self.gbCalificacion)
        self.optM.setGeometry(QtCore.QRect(20, 110, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.optM.setFont(font)
        self.optM.setObjectName("optM")
        self.lbPromedio = QtWidgets.QLabel(self.centralwidget)
        self.lbPromedio.setGeometry(QtCore.QRect(30, 270, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbPromedio.setFont(font)
        self.lbPromedio.setObjectName("lbPromedio")
        self.lePromedio = QtWidgets.QLineEdit(self.centralwidget)
        self.lePromedio.setGeometry(QtCore.QRect(190, 270, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lePromedio.setFont(font)
        self.lePromedio.setObjectName("lePromedio")
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(380, 220, 91, 51))
        self.btnCerrar.setObjectName("btnCerrar")
        self.tblEncuesta = QtWidgets.QTableWidget(self.centralwidget)
        self.tblEncuesta.setGeometry(QtCore.QRect(10, 330, 481, 181))
        self.tblEncuesta.setColumnCount(5)
        self.tblEncuesta.setObjectName("tblEncuesta")
        self.tblEncuesta.setRowCount(0)
        self.tblEncuesta.horizontalHeader().setDefaultSectionSize(95)
        self.lePromedio_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lePromedio_2.setGeometry(QtCore.QRect(190, 530, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lePromedio_2.setFont(font)
        self.lePromedio_2.setObjectName("lePromedio_2")
        self.lbPromedio_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbPromedio_2.setGeometry(QtCore.QRect(30, 530, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbPromedio_2.setFont(font)
        self.lbPromedio_2.setObjectName("lbPromedio_2")
        self.pbrEncuesta = QtWidgets.QProgressBar(self.centralwidget)
        self.pbrEncuesta.setGeometry(QtCore.QRect(10, 310, 481, 16))
        self.pbrEncuesta.setProperty("value", 0)
        self.pbrEncuesta.setTextVisible(True)
        self.pbrEncuesta.setObjectName("pbrEncuesta")
        frmEncuesta.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmEncuesta)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName("menubar")
        frmEncuesta.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmEncuesta)
        self.statusbar.setObjectName("statusbar")
        frmEncuesta.setStatusBar(self.statusbar)

        self.retranslateUi(frmEncuesta)
        QtCore.QMetaObject.connectSlotsByName(frmEncuesta)

    def retranslateUi(self, frmEncuesta):
        _translate = QtCore.QCoreApplication.translate
        frmEncuesta.setWindowTitle(_translate("frmEncuesta", "Datos de Encuesta"))
        self.btnRegistrar.setText(_translate("frmEncuesta", "Registrar"))
        self.btnRestablecer.setText(_translate("frmEncuesta", "Restablecer"))
        self.btnEvaluar.setText(_translate("frmEncuesta", "Evaluar"))
        self.lbVehiculo.setText(_translate("frmEncuesta", "Tipo de Vehículo Alquilado"))
        self.lbDias.setText(_translate("frmEncuesta", "Cantidad de Días Alquilado"))
        self.lbKm.setText(_translate("frmEncuesta", "Cantidad de Kilómetros"))
        self.gbCalificacion.setTitle(_translate("frmEncuesta", "Calificación del Servicio"))
        self.optMB.setText(_translate("frmEncuesta", "Muy Bueno"))
        self.optB.setText(_translate("frmEncuesta", "Bueno"))
        self.optR.setText(_translate("frmEncuesta", "Regular"))
        self.optM.setText(_translate("frmEncuesta", "Malo"))
        self.lbPromedio.setText(_translate("frmEncuesta", "Evaluación"))
        self.btnCerrar.setText(_translate("frmEncuesta", "Cerrar"))
        self.lbPromedio_2.setText(_translate("frmEncuesta", "Evaluación Promedio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmEncuesta = QtWidgets.QMainWindow()
    ui = Ui_frmEncuesta()
    ui.setupUi(frmEncuesta)
    frmEncuesta.show()
    sys.exit(app.exec_())

