# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_covid4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmCovid(object):
    def setupUi(self, frmCovid):
        frmCovid.setObjectName("frmCovid")
        frmCovid.resize(490, 468)
        frmCovid.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(frmCovid)
        self.centralwidget.setObjectName("centralwidget")
        self.gbSexo = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSexo.setGeometry(QtCore.QRect(30, 10, 151, 81))
        self.gbSexo.setObjectName("gbSexo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gbSexo)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutSexo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutSexo.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutSexo.setObjectName("verticalLayoutSexo")
        self.optF = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.optF.setChecked(True)
        self.optF.setObjectName("optF")
        self.verticalLayoutSexo.addWidget(self.optF)
        self.optM = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.optM.setObjectName("optM")
        self.verticalLayoutSexo.addWidget(self.optM)
        self.gbEdad = QtWidgets.QGroupBox(self.centralwidget)
        self.gbEdad.setGeometry(QtCore.QRect(200, 10, 151, 81))
        self.gbEdad.setObjectName("gbEdad")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbEdad)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 131, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayoutEdad = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayoutEdad.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutEdad.setObjectName("verticalLayoutEdad")
        self.optMenor = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.optMenor.setChecked(True)
        self.optMenor.setObjectName("optMenor")
        self.verticalLayoutEdad.addWidget(self.optMenor)
        self.optMayor = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.optMayor.setObjectName("optMayor")
        self.verticalLayoutEdad.addWidget(self.optMayor)
        self.btnEvaluar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvaluar.setGeometry(QtCore.QRect(370, 30, 101, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEvaluar.setFont(font)
        self.btnEvaluar.setObjectName("btnEvaluar")
        self.btnRestablecer = QtWidgets.QPushButton(self.centralwidget)
        self.btnRestablecer.setGeometry(QtCore.QRect(370, 120, 101, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnRestablecer.setFont(font)
        self.btnRestablecer.setObjectName("btnRestablecer")
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(370, 210, 101, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCerrar.setFont(font)
        self.btnCerrar.setObjectName("btnCerrar")
        self.Probabilidad = QtWidgets.QLabel(self.centralwidget)
        self.Probabilidad.setGeometry(QtCore.QRect(20, 310, 71, 16))
        self.Probabilidad.setObjectName("Probabilidad")
        self.Sintomas = QtWidgets.QLabel(self.centralwidget)
        self.Sintomas.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.Sintomas.setObjectName("Sintomas")
        self.chkCansancio = QtWidgets.QCheckBox(self.centralwidget)
        self.chkCansancio.setGeometry(QtCore.QRect(70, 120, 160, 17))
        self.chkCansancio.setObjectName("chkCansancio")
        self.chkRespirar = QtWidgets.QCheckBox(self.centralwidget)
        self.chkRespirar.setGeometry(QtCore.QRect(70, 180, 160, 17))
        self.chkRespirar.setObjectName("chkRespirar")
        self.chkTos = QtWidgets.QCheckBox(self.centralwidget)
        self.chkTos.setGeometry(QtCore.QRect(70, 210, 160, 17))
        self.chkTos.setObjectName("chkTos")
        self.chkCabeza = QtWidgets.QCheckBox(self.centralwidget)
        self.chkCabeza.setGeometry(QtCore.QRect(70, 150, 160, 17))
        self.chkCabeza.setObjectName("chkCabeza")
        self.chkMuscular = QtWidgets.QCheckBox(self.centralwidget)
        self.chkMuscular.setGeometry(QtCore.QRect(70, 270, 160, 17))
        self.chkMuscular.setObjectName("chkMuscular")
        self.chkGusto = QtWidgets.QCheckBox(self.centralwidget)
        self.chkGusto.setGeometry(QtCore.QRect(70, 240, 160, 17))
        self.chkGusto.setObjectName("chkGusto")
        self.lblProbabilidad = QtWidgets.QLabel(self.centralwidget)
        self.lblProbabilidad.setGeometry(QtCore.QRect(100, 310, 111, 21))
        self.lblProbabilidad.setFrameShape(QtWidgets.QFrame.Box)
        self.lblProbabilidad.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblProbabilidad.setText("")
        self.lblProbabilidad.setObjectName("lblProbabilidad")
        self.lstResultados = QtWidgets.QListWidget(self.centralwidget)
        self.lstResultados.setGeometry(QtCore.QRect(100, 340, 111, 81))
        self.lstResultados.setObjectName("lstResultados")
        self.Resultado = QtWidgets.QLabel(self.centralwidget)
        self.Resultado.setGeometry(QtCore.QRect(20, 340, 47, 13))
        self.Resultado.setObjectName("Resultado")
        self.gbBloquear = QtWidgets.QGroupBox(self.centralwidget)
        self.gbBloquear.setEnabled(True)
        self.gbBloquear.setGeometry(QtCore.QRect(240, 100, 111, 201))
        self.gbBloquear.setCheckable(True)
        self.gbBloquear.setObjectName("gbBloquear")
        self.spbTos = QtWidgets.QSpinBox(self.gbBloquear)
        self.spbTos.setGeometry(QtCore.QRect(30, 110, 42, 22))
        self.spbTos.setObjectName("spbTos")
        self.spbMuscular = QtWidgets.QSpinBox(self.gbBloquear)
        self.spbMuscular.setGeometry(QtCore.QRect(30, 170, 42, 22))
        self.spbMuscular.setObjectName("spbMuscular")
        self.spbCansancio = QtWidgets.QDoubleSpinBox(self.gbBloquear)
        self.spbCansancio.setGeometry(QtCore.QRect(30, 20, 62, 22))
        self.spbCansancio.setObjectName("spbCansancio")
        self.spbGusto = QtWidgets.QSpinBox(self.gbBloquear)
        self.spbGusto.setGeometry(QtCore.QRect(30, 140, 42, 22))
        self.spbGusto.setObjectName("spbGusto")
        self.spbRespirar = QtWidgets.QSpinBox(self.gbBloquear)
        self.spbRespirar.setGeometry(QtCore.QRect(30, 80, 42, 21))
        self.spbRespirar.setObjectName("spbRespirar")
        self.spbCabeza = QtWidgets.QDoubleSpinBox(self.gbBloquear)
        self.spbCabeza.setGeometry(QtCore.QRect(30, 50, 62, 22))
        self.spbCabeza.setObjectName("spbCabeza")
        frmCovid.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmCovid)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 21))
        self.menubar.setObjectName("menubar")
        frmCovid.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmCovid)
        self.statusbar.setObjectName("statusbar")
        frmCovid.setStatusBar(self.statusbar)

        self.retranslateUi(frmCovid)
        QtCore.QMetaObject.connectSlotsByName(frmCovid)

    def retranslateUi(self, frmCovid):
        _translate = QtCore.QCoreApplication.translate
        frmCovid.setWindowTitle(_translate("frmCovid", "Probabilidad Covid Persistente"))
        self.gbSexo.setTitle(_translate("frmCovid", "Sexo"))
        self.optF.setText(_translate("frmCovid", "Femenino"))
        self.optM.setText(_translate("frmCovid", "Masculino"))
        self.gbEdad.setTitle(_translate("frmCovid", "Edad"))
        self.optMenor.setText(_translate("frmCovid", "Menor 60"))
        self.optMayor.setText(_translate("frmCovid", "Mayor 60"))
        self.btnEvaluar.setText(_translate("frmCovid", "Evaluar"))
        self.btnRestablecer.setText(_translate("frmCovid", "Restablecer"))
        self.btnCerrar.setText(_translate("frmCovid", "Cerrar"))
        self.Probabilidad.setText(_translate("frmCovid", "Probabilidad"))
        self.Sintomas.setText(_translate("frmCovid", "Síntomas"))
        self.chkCansancio.setText(_translate("frmCovid", "Cansancio"))
        self.chkRespirar.setText(_translate("frmCovid", "Dificultad Para Respirar"))
        self.chkTos.setText(_translate("frmCovid", "Tos Persistente"))
        self.chkCabeza.setText(_translate("frmCovid", "Dolor de Cabeza"))
        self.chkMuscular.setText(_translate("frmCovid", "DolorMuscular"))
        self.chkGusto.setText(_translate("frmCovid", "Sentido del Gusto Disminuido"))
        self.Resultado.setText(_translate("frmCovid", "Resultados"))
        self.gbBloquear.setTitle(_translate("frmCovid", "Bloquear Valores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmCovid = QtWidgets.QMainWindow()
    ui = Ui_frmCovid()
    ui.setupUi(frmCovid)
    frmCovid.show()
    sys.exit(app.exec_())

